# Generated by Django 4.0.4 on 2022-06-16 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ttowner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TTUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Atalho')),
                ('unittype', models.CharField(blank=True, max_length=20, null=True)),
                ('zipcode', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('address1', models.CharField(max_length=100, null=True)),
                ('county', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('st', models.CharField(max_length=2, null=True)),
                ('status', models.CharField(choices=[('R', 'Rented'), ('S', 'Sold'), ('A', 'Available')], default='A', max_length=8)),
                ('active', models.BooleanField(default=False)),
                ('businessdate', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('modal', models.CharField(choices=[('R', 'Rent'), ('S', 'Sell')], default='R', max_length=8)),
                ('bedroom', models.CharField(blank=True, max_length=2, null=True)),
                ('restroom', models.CharField(blank=True, max_length=2, null=True)),
                ('petpolicy', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, max_length=4000, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='unit_ttowner', to='ttowner.ttowner')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='parentid_ttunit', to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ('id',),
            },
        ),
    ]
