# Generated by Django 4.0.4 on 2022-06-06 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttunit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ttunit',
            options={'ordering': ('id',), 'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
    ]
