# Generated by Django 4.0.4 on 2022-06-06 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttcompany', '0003_alter_ttcompany_username'),
        ('ttunit', '0002_alter_ttunit_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttunit',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ttunit',
            name='address1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ttunit',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ttunit',
            name='county',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ttunit',
            name='st',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='ttunit',
            name='zipcode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ttunit',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ttcompany', to='ttcompany.ttcompany'),
        ),
    ]
