# Generated by Django 4.0.4 on 2022-06-07 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttowner', '0002_remove_ttowner_unit_ttowner_username'),
        ('ttunit', '0003_ttunit_address_ttunit_address1_ttunit_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttunit',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ttowner', to='ttowner.ttowner'),
            preserve_default=False,
        ),
    ]
