# Generated by Django 4.0.4 on 2022-06-07 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttunit', '0004_ttunit_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ttunit',
            name='owner',
        ),
    ]
