# Generated by Django 4.0.4 on 2022-06-07 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttunit', '0004_ttunit_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ttunit',
            old_name='restrooom',
            new_name='restroom',
        ),
    ]
