# Generated by Django 4.0.4 on 2022-06-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttunit', '0005_rename_restrooom_ttunit_restroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttunit',
            name='description',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
    ]
