# Generated by Django 4.0.4 on 2022-06-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttunit', '0006_ttunit_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttunit',
            name='bedroom',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ttunit',
            name='restroom',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
