# Generated by Django 4.0.4 on 2022-06-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttunit', '0007_alter_ttunit_bedroom_alter_ttunit_restroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttunit',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Atalho'),
        ),
    ]
