# Generated by Django 4.0.4 on 2022-06-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttunit', '0008_alter_ttunit_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttunit',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
