# Generated by Django 4.0.4 on 2022-05-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('period', models.CharField(blank=True, max_length=10, null=True)),
                ('display', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-create_at',),
                'abstract': False,
            },
        ),
    ]
