# Generated by Django 4.0.4 on 2022-05-05 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='coursename',
            new_name='name',
        ),
    ]
