# Generated by Django 4.0.4 on 2022-05-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_options_course_pkcourse_name_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='mingrade',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
