# Generated by Django 4.0.4 on 2022-06-16 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ttcompany.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TTCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(default='posts/noimage.jpg', upload_to=ttcompany.models.upload_to, verbose_name='Image')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('codearea', models.CharField(max_length=3)),
                ('phone', models.CharField(max_length=10)),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='username_ttcompany_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ('name',),
            },
        ),
        migrations.AddConstraint(
            model_name='ttcompany',
            constraint=models.UniqueConstraint(fields=('name', 'username'), name='PKCompany_Name_UserName'),
        ),
    ]
