# Generated by Django 4.0.4 on 2022-06-05 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttcompany', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ttcompany',
            old_name='codeare',
            new_name='codearea',
        ),
    ]
