# Generated by Django 4.0.4 on 2022-06-24 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttcompany', '0002_plan_ttcompany_plan_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ttcompany',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='ttcompany',
            name='plan_status',
        ),
        migrations.RemoveField(
            model_name='ttcompany',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='ttcompany',
            name='stripe_subscription_id',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
