# Generated by Django 4.0.4 on 2022-05-11 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cost_center', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costcenter',
            old_name='costcenter',
            new_name='cost_center',
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='username_cost_center_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
