# Generated by Django 4.0.4 on 2022-05-06 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='username_instructor_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
