# Generated by Django 4.0.4 on 2022-05-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_alter_instructor_username'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='instructor',
            constraint=models.UniqueConstraint(fields=('name', 'username'), name='PKInstructor_Name_UserName'),
        ),
    ]
