# Generated by Django 4.0.4 on 2022-06-16 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TTowner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Atalho')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('zipcode', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('address1', models.CharField(max_length=100, null=True)),
                ('county', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('st', models.CharField(max_length=2, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('codearea', models.CharField(max_length=3)),
                ('phone', models.CharField(max_length=10)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='superuser_ttowner', to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='username_ttowner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Owner',
                'verbose_name_plural': 'Owners',
                'ordering': ('last_name',),
            },
        ),
        migrations.AddConstraint(
            model_name='ttowner',
            constraint=models.UniqueConstraint(fields=('email', 'username'), name='PKOwner_Email_UserName'),
        ),
    ]
