# Generated by Django 4.0.4 on 2022-06-06 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ttunit', '0003_ttunit_address_ttunit_address1_ttunit_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTowner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True, verbose_name='Atalho')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('zipcode', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('address1', models.CharField(max_length=100, null=True)),
                ('county', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('st', models.CharField(max_length=2, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('codearea', models.CharField(max_length=3)),
                ('phone', models.CharField(max_length=10)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ttowner', to='ttunit.ttunit')),
            ],
            options={
                'verbose_name': 'Owner',
                'verbose_name_plural': 'Owners',
                'ordering': ('last_name',),
            },
        ),
    ]
