# Generated by Django 4.0.4 on 2022-06-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttowner', '0002_remove_ttowner_unit_ttowner_username'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ttowner',
            constraint=models.UniqueConstraint(fields=('email', 'username'), name='PKOwner_Email_UserName'),
        ),
    ]
