# Generated by Django 4.0.4 on 2022-06-14 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttcompany', '0003_alter_ttcompany_username'),
        ('ttowner', '0004_alter_ttowner_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttowner',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_ttowner', to='ttcompany.ttcompany'),
            preserve_default=False,
        ),
    ]
