# Generated by Django 4.0.4 on 2022-06-15 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ttowner', '0005_ttowner_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ttowner',
            name='company',
        ),
        migrations.AddField(
            model_name='ttowner',
            name='superuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='superuser_ttowner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
