# Generated by Django 4.0.4 on 2022-06-15 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttowner', '0006_remove_ttowner_company_ttowner_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ttowner',
            old_name='superuser',
            new_name='parent_id',
        ),
    ]
