# Generated by Django 4.0.4 on 2022-04-28 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='parent',
        ),
    ]
