# Generated by Django 4.0.4 on 2022-06-05 02:44

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cargo',
            field=models.CharField(blank=True, max_length=150, verbose_name='cargo'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='people/noimage.jpg', upload_to=authentication.models.upload_to, verbose_name='Image'),
        ),
    ]
