# Generated by Django 4.0.4 on 2022-06-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_cargo_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='typeofuser',
            field=models.CharField(choices=[('P', 'People'), ('C', 'Company')], default='P', max_length=8),
        ),
    ]
