# Generated by Django 4.0.4 on 2022-04-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcao',
            name='superusuario',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
