# Generated by Django 4.0.4 on 2022-05-05 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcao', '0003_remove_funcao_superusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcao',
            old_name='nomefuncao',
            new_name='name',
        ),
    ]
