# Generated by Django 4.0.4 on 2022-06-07 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ttcompany', '0003_alter_ttcompany_username'),
        ('ttunit', '0004_ttunit_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTlead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True, verbose_name='Atalho')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('codearea', models.CharField(max_length=3)),
                ('phone', models.CharField(max_length=10)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ttcompany_ttlead', to='ttcompany.ttcompany')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ttunit_ttlead', to='ttunit.ttunit')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ('last_name',),
            },
        ),
        migrations.AddConstraint(
            model_name='ttlead',
            constraint=models.UniqueConstraint(fields=('email', 'first_name', 'unit'), name='PKLead_Email_first_name_Unit'),
        ),
    ]
