# Generated by Django 4.0.4 on 2022-06-07 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttunit', '0003_ttunit_address_ttunit_address1_ttunit_city_and_more'),
        ('ttlead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttlead',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ttunit', to='ttunit.ttunit'),
        ),
    ]
