# Generated by Django 4.0.4 on 2022-06-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttlead', '0002_alter_ttlead_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttlead',
            name='sentemail',
            field=models.BooleanField(default=False),
        ),
    ]
