# Generated by Django 4.0.4 on 2022-06-22 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ttlead', '0002_remove_ttlead_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttlead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignedleads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ttlead',
            name='confidence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ttlead',
            name='estimated_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ttlead',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=25),
        ),
        migrations.AddField(
            model_name='ttlead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('inprogress', 'In progress'), ('lost', 'Lost'), ('won', 'Won')], default='new', max_length=25),
        ),
    ]
