# Generated by Django 4.0.4 on 2022-06-26 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ttlead', '0003_ttlead_assigned_to_ttlead_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttlead',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parentid_lead', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ttlead',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='username_lead', to=settings.AUTH_USER_MODEL),
        ),
    ]
