# Generated by Django 4.0.4 on 2022-06-08 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttlead', '0003_ttlead_sentemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ttlead',
            old_name='sentemail',
            new_name='sent_email',
        ),
    ]
