# Generated by Django 4.0.4 on 2022-06-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttlead', '0004_rename_sentemail_ttlead_sent_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttlead',
            name='message',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
    ]
