# Generated by Django 4.0.4 on 2022-05-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequency', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='frequency',
            constraint=models.UniqueConstraint(fields=('name', 'username'), name='PKFrequency_Name_UserName'),
        ),
    ]
