# Generated by Django 4.0.4 on 2022-05-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequency', '0002_frequency_pkfrequency_name_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequency',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
