# Generated by Django 4.0.4 on 2022-05-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0002_rename_mostrar_position_display'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ('name',), 'verbose_name': 'Position', 'verbose_name_plural': 'Positions'},
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('name', 'username'), name='PKPosition_Name_UserName'),
        ),
    ]
