# Generated by Django 4.0.4 on 2022-06-16 19:22

from django.db import migrations, models
import django.db.models.deletion
import ttunitimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ttunit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTUnitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(default='units/noimage.jpg', upload_to=ttunitimage.models.upload_to, verbose_name='Image')),
                ('description', models.TextField(blank=True, max_length=4000, null=True)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ttunit_image', to='ttunit.ttunit')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ('unit',),
            },
        ),
    ]
