# Generated by Django 4.0.4 on 2022-06-17 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ttunitimage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ttunitimage',
            name='description',
        ),
        migrations.AddField(
            model_name='ttunitimage',
            name='parent_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='photo_ttunit', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ttunitimage',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
