# Generated by Django 4.0.4 on 2022-06-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttunitimage', '0003_ttunitimage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttunitimage',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
