# Generated by Django 4.0.4 on 2022-06-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttunitimage', '0004_ttunitimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttunitimage',
            name='principal',
            field=models.BooleanField(default=False),
        ),
    ]
